### ISSUE TITLE
Initial value of model properties should be "default value" from spec.

### ISSUE THREAD

**Issue by lievendf** [ai4you-io/openedge-abl-openapi#30]
Currently API body elements that are marked as nullable get an initial value of ? in the generated model, and this value always gets sent in the request. 
I'm not sure this is correct.
Initial value should map to [default value](https://swagger.io/docs/specification/v3_0/describing-parameters/#default-parameter-values).
Being nullable does not imply that the initial value is null.
There is also no distinction between not specifying a value for a property (i.e. I do not want it to be sent in the request) and setting it explicitly to a value (null or other). In all cases the property value is added in the request.

**Comment by mstab** [comment]
Thank you for bringing this to our attention.

You're absolutely right, a nullable property should not be initialised with `?` by default. \
This is a bug in the current codegen, and I will change it.

Regarding including properties in the JSON output:

Proposed fix:
- Add a private `JsonObject` property to each model.
- On every `Set{Property}()`, call `json:Add("prop", value)` or `json:AddNull("prop")`.
- `ToJson()` simply writes the pre-built `json` object.

This ensures:
- Only explicitly set properties are included.
- Explicit `null` (`SetX(?)`) → sent as `null`.
- Unset optional properties → omitted.

In case it is useful to have a global setting for models to always return all properties when `ToJson()` is called, this can be added as it might be useful during development to work with complete models.

**Comment by mstab** [comment]
The nullable properties will not get an initial value of `?` anymore.

This has been solved in `preview`.

**Comment by mstab** [comment]
To have a more robust implementation for defaults and how serialization is handled, I have implemented it as such (Only for server, will be implemented for client as soon as possible):

### New config options added to the `ConfigManager`: 
- **`emitDefaults`** (boolean, default: false): Include default values in JSON output when not explicitly set.
- **`omitEmptyCollections`** (boolean, default: false): Omit empty arrays/maps from JSON output. When `true`, empty collections are excluded from serialization.
- **`omitNulls`** (boolean, default: false): Omit null values from JSON output. When `true`, properties with null/unknown values are excluded.

If the configuration for serialization is set as follows, it will always include all properties of the model:
```json
{
  "serialization": {
    "emitDefaults": true,
    "omitEmptyCollections": false,
    "omitNulls": false
  }
}
```

### Model Builders have extra methods to set defaults
- **`WithDefaults()`** will set all defaults defined in the spec
- **`WithDefault{propertyName}()`** will set only the specific default for that property.

```java
oResult:SetOk(new OrderBuilder()
    :WithDefaults()  // all defaults will be set
    :SetOrderDate(now) // In this case OrderDate also has a default value, but we can overwrite it via the setters (calling order matters)
    :AddOrderItem(new OrderItemBuilder()  // either pass in a builder, no need to call build
        :SetProductId(1)
        :SetQuantity(5)
    )
    :AddOrderItem(new OrderItem(2, 10))  // or pass in the object directly, useful for small models
    :Build()
).
```

_Note: At this moment, only defaults for primitive data types are handled. I will address this limitation in a future iteration._

This is now available in `preview`.
In case you have any comments, please let us know.

**Comment by lievendf** [comment]
> Only for server, will be implemented for client as soon as possible

We're needing this for the client to continue. Do you have an ETA?

Edit: I'm getting the following error when trying to generate server code and nothing is generated/downloaded:
Error: Null check operator used on a null value
<img width="320" height="44" alt="Image" src="https://github.com/user-attachments/assets/0e0d2432-fdb4-47d2-983e-79ad9e66bafc" />
Did I configure something wrong?
I did not get this error with the previous version of the generator...

**Comment by mstab** [comment]
> We're needing this for the client to continue. Do you have an ETA?

Will start working on the implementation for client today, hoping to finalize it this week.

> Error: Null check operator used on a null value

This is an error coming from the UI, will see what is causing this.
Could you provide some more details about the setup?
- Using a workspace?
- What settings were used? (Client/Server)
  Any specifics, different from your previous runs?

**Comment by mstab** [comment]
After some testing, I possibly found the culprit:

When you have used the generator, all generations with unique generator type + language + spec, will be kept in the settings.json.
But when a path referenced in there doesn't exist anymore, it fails.

A possible solution to continue while we push a fix: 
- Open `.vscode/settings.json`
- Look for entries using a reference to a non-existing path
- Remove that whole entry (or change the paths to valid ones)
- Reload the extension

In case this doesn't help, please let me know.

Meanwhile we continue looking for a solution

**Comment by lievendf** [comment]
I don't think a non-existing path is the problem:
- all paths used previously still exist
- there is not even a .vscode/settings.json file present (while the generator does say that the settings are saved in settings.json).

The problem only seems to occur when generating server side code, not for the client...

**Comment by mstab** [comment]
We have published a new version of the extension, `v0.1.48`.

In case this doesn't resolve your issue, please let us know.

**Comment by lievendf** [comment]
> Will start working on the implementation for client today, hoping to finalize it this week.

Any news on this? We really need this to be able to continue.
Thanks!
